# Generated by Django 3.0.3 on 2021-02-05 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_no', models.CharField(default=None, help_text='Enter student number', max_length=10)),
                ('first_name', models.CharField(default=None, help_text='Enter first name', max_length=20)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=20)),
                ('class_no', models.CharField(help_text='Enter class number', max_length=10)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique id for this teacher', primary_key=True, serialize=False)),
                ('staff_no', models.CharField(help_text='Enter staff number', max_length=10)),
                ('full_name', models.CharField(default=None, help_text='Enter teacher full name', max_length=30)),
                ('level', models.CharField(help_text='Enter teacher level', max_length=10)),
                ('class_held', models.CharField(help_text='Enter class number', max_length=10)),
            ],
        ),
    ]
