# Generated by Django 3.0.3 on 2021-02-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contoso', '0002_teacher_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='level',
            field=models.CharField(blank=True, help_text='Enter teacher level', max_length=10),
        ),
    ]
