# Generated by Django 3.0.3 on 2021-02-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contoso', '0003_auto_20210206_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_held',
            field=models.CharField(blank=True, help_text='Enter class number', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='level',
            field=models.CharField(help_text='Enter teacher level', max_length=10),
        ),
    ]
